=== Docrong/GGR/workspaceHB/eoms35/WebContent/portal/config/portlet-config.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--W3C Schema generated by XMLSpy v2006 rel. 3 U (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="allowJS">
		<xs:simpleType>
			<xs:restriction base="xs:boolean"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="autoRefreshed">
		<xs:simpleType>
			<xs:restriction base="xs:boolean"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="configMode">
		<xs:simpleType>
			<xs:restriction base="xs:boolean"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="editMode">
		<xs:simpleType>
			<xs:restriction base="xs:boolean"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="helpMode">
		<xs:simpleType>
			<xs:restriction base="xs:boolean"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="icon">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="name">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="pageRefreshed">
		<xs:simpleType>
			<xs:restriction base="xs:boolean"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="parameter">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="name"/>
				<xs:element ref="value"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="path">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="periodTime">
		<xs:simpleType>
			<xs:restriction base="xs:integer"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="tag">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="portlet">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="name"/>
				<xs:element ref="path"/>
				<xs:element ref="title"/>
				<xs:element ref="icon"/>
				<xs:element ref="url"/>
				<xs:element ref="tag"/>
				<xs:element ref="refreshMode"/>
				<xs:element ref="editMode"/>
				<xs:element ref="helpMode"/>
				<xs:element ref="configMode"/>
				<xs:element ref="autoRefreshed"/>
				<xs:element ref="periodTime"/>
				<xs:element ref="allowJS"/>
				<xs:element ref="pageRefreshed"/>
				<xs:element ref="showNumber" minOccurs="0"/>
				<xs:element ref="parameter" minOccurs="0"/>
				<xs:element ref="roles" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="roles">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="role" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="role">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="portlets">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="portlet" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="refreshMode">
		<xs:simpleType>
			<xs:restriction base="xs:boolean"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="showNumber">
		<xs:simpleType>
			<xs:restriction base="xs:integer"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="title">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="url" type="xs:string"/>
	<xs:element name="value" type="xs:string"/>
</xs:schema>

=== Docrong/GGR/workspaceHB/eoms35/WebContent/portal/config/portlet-config.xml
<?xml version="1.0" encoding="GB2312"?>
<portlets xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="portlet-config.xsd">
	<portlet>
	    <name>JFreeChartDemoPortlet</name>
		<path>/JFreeChartDemoPortlet.lp</path>
		<title>JFreeChart Demo</title>
		<icon></icon>
		<url/>
		<tag>default</tag>
		<refreshMode>false</refreshMode>
		<editMode>true</editMode>
		<helpMode>false</helpMode>
		<configMode>false</configMode>
		<autoRefreshed>false</autoRefreshed>
		<periodTime>0</periodTime>
		<allowJS>true</allowJS>
		<pageRefreshed>false</pageRefreshed>
		<role>role_member,role_public,role_admin</role>
	</portlet>

	<portlet>
	    <name>searchPortlet</name>
		<path>/searchPortlet.lp</path>
		<title>portlet.title.search</title>
		<icon>/portal/light/images/search.gif</icon>
		<url/>
		<tag>default</tag>
		<refreshMode>false</refreshMode>
		<editMode>false</editMode>
		<helpMode>false</helpMode>
		<configMode>false</configMode>
		<autoRefreshed>false</autoRefreshed>
		<periodTime>0</periodTime>
		<allowJS>true</allowJS>
		<pageRefreshed>false</pageRefreshed>
		<role>role_member,role_public,role_admin</role>
	</portlet>
	<portlet>
	    <name>weatherPortlet</name>
		<path>/weatherPortlet.lp</path>
		<title>portlet.title.weather</title>
		<icon>/portal/light/images/weather.gif</icon>
		<url/>
		<tag>default</tag>
		<refreshMode>true</refreshMode>
		<editMode>true</editMode>
		<helpMode>false</helpMode>
		<configMode>false</configMode>
		<autoRefreshed>false</autoRefreshed>
		<periodTime>0</periodTime>
		<allowJS>false</allowJS>
		<pageRefreshed>false</pageRefreshed>
		<role>role_member,role_admin</role>
	</portlet>
	<portlet>
	    <name>bookmarkPortlet</name>
		<path>/bookmarkPortlet.lp</path>
		<title>portlet.title.bookmark</title>
		<icon>/portal/light/images/bookmark.gif</icon>
		<url/>
		<tag>default</tag>
		<refreshMode>false</refreshMode>
		<editMode>true</editMode>
		<helpMode>false</helpMode>
		<configMode>false</configMode>
		<autoRefreshed>false</autoRefreshed>
		<periodTime>0</periodTime>
		<allowJS>false</allowJS>
		<pageRefreshed>false</pageRefreshed>
		<role>role_admin</role>
	</portlet>
<!-- 20070422 zhoucz start -->
	<portlet>
	    <name>webSystemPortlet</name>
		<path>/webSystemPortlet.lp</path>
		<title>portlet.title.websystem</title>
		<icon>/portal/light/images/bookmark.gif</icon>
		<url/>
		<tag>default</tag>
		<refreshMode>true</refreshMode>
		<editMode>false</editMode>
		<helpMode>false</helpMode>
		<configMode>false</configMode>
		<autoRefreshed>false</autoRefreshed>
		<periodTime>0</periodTime>
		<allowJS>false</allowJS>
		<pageRefreshed>false</pageRefreshed>
		<role>role_admin,role_member</role>
	</portlet>
<!-- 20070422 end -->
	<portlet>
	    <name>notePortlet</name>
		<path>/notePortlet.lp</path>
		<title>portlet.title.note</title>
		<icon>/portal/light/images/note.gif</icon>
		<url/>
		<tag>default</tag>
		<refreshMode>false</refreshMode>
		<editMode>true</editMode>
		<helpMode>false</helpMode>
		<configMode>false</configMode>
		<autoRefreshed>false</autoRefreshed>
		<periodTime>0</periodTime>
		<allowJS>false</allowJS>
		<pageRefreshed>false</pageRefreshed>
		<role>role_member,role_public,role_admin</role>
	</portlet>
	<portlet>
	    <name>yahooSports</name>
		<path>/rssPortlet.lp</path>
		<title>portlet.title.sports.yahoo</title>
		<icon></icon>
		<url>http://www.yahoo.com/</url>
		<tag>portlet.tag.title.sports</tag>
		<refreshMode>true</refreshMode>
		<editMode>true</editMode>
		<helpMode>false</helpMode>
		<configMode>false</configMode>
		<autoRefreshed>false</autoRefreshed>
		<periodTime>0</periodTime>
		<allowJS>false</allowJS>
		<pageRefreshed>false</pageRefreshed>
		<showNumber>6</showNumber>
		<parameter>
			<name>feed</name>
			<value>http://rss.news.yahoo.com/rss/sports</value>
		</parameter>
		<role>role_admin</role>
	</portlet>
    <!--工单部分-->
    <portlet>
	    <name>worksheetlist</name>
		<path>/webPagePortlet.lp</path>
		<title>工单列表</title>
		<icon>/portal/light/images/table.gif</icon>
		<url>/wfworksheet/Liantongsheet/listAllTasksUndo.do</url>
		<tag>portlet.tag.title.worksheet</tag>
		<refreshMode>true</refreshMode>
		<editMode>false</editMode>
		<helpMode>false</helpMode>
		<configMode>false</configMode>
		<autoRefreshed>false</autoRefreshed>
		<periodTime>0</periodTime>
		<allowJS>false</allowJS>
		<pageRefreshed>false</pageRefreshed>
		<showNumber>200</showNumber>
        <parameter>
			<name>url</name>
			<value>/wfworksheet/Liantongsheet/listAllTasksUndo.do</value>
        </parameter>
        <role>role_member,role_admin</role>
    </portlet>
    <portlet>
	    <name>todoTasklist</name>
		<path>/webPagePortlet.lp</path>
		<title>待处理工单列表</title>
		<icon>/portal/light/images/table.gif</icon>
		<url>/template/affair.jsp</url>
		<tag>portlet.tag.title.worksheet</tag>
		<refreshMode>true</refreshMode>
		<editMode>false</editMode>
		<helpMode>false</helpMode>
		<configMode>false</configMode>
		<autoRefreshed>false</autoRefreshed>
		<periodTime>0</periodTime>
		<allowJS>false</allowJS>
		<pageRefreshed>false</pageRefreshed>
		<showNumber>240</showNumber>
        <parameter>
			<name>url</name>
			<value>/template/affair.jsp</value>
        </parameter>
        <role>role_member,role_admin</role>
    </portlet>
    <!--作业计划部分-->
    <portlet>
	    <name>workplan</name>
		<path>/webPagePortlet.lp</path>
		<title>未处理作业计划列表</title>
		<icon>/portal/light/images/table.gif</icon>
		<url>/workplan/tawwpexecute/countuser.do</url>
		<tag>portlet.tag.title.workplan</tag>
		<refreshMode>true</refreshMode>
		<editMode>false</editMode>
		<helpMode>false</helpMode>
		<configMode>false</configMode>
		<autoRefreshed>false</autoRefreshed>
		<periodTime>0</periodTime>
		<allowJS>false</allowJS>
		<pageRefreshed>false</pageRefreshed>
		<showNumber>200</showNumber>
        <parameter>
			<name>url</name>
			<value>/workplan/tawwpexecute/countuser.do</value>
        </parameter>
      	<role>role_admin</role>
    </portlet>
    <portlet>
	    <name>dailyexecutelist</name>
		<path>/webPagePortlet.lp</path>
		<title>日常作业计划列表</title>
		<icon>/portal/light/images/table.gif</icon>
		<url>/workplan/tawwpexecute/dailyexecutelist.do</url>
		<tag>portlet.tag.title.workplan</tag>
		<refreshMode>true</refreshMode>
		<editMode>false</editMode>
		<helpMode>false</helpMode>
		<configMode>false</configMode>
		<autoRefreshed>false</autoRefreshed>
		<periodTime>0</periodTime>
		<allowJS>false</allowJS>
		<pageRefreshed>false</pageRefreshed>
		<showNumber>200</showNumber>
        <parameter>
			<name>url</name>
			<value>/workplan/tawwpexecute/dailyexecutelist.do</value>
        </parameter>
        <role>role_member,role_admin</role>
    </portlet>
    <portlet>
	    <name>proxy_manage</name>
		<path>/webPagePortlet.lp</path>
		<title>代维管理</title>
		<icon>/portal/light/images/app.gif</icon>
		<url>/TawDept/proxy_manage.do</url>
		<tag>portlet.tag.title.workplan</tag>
		<refreshMode>true</refreshMode>
		<editMode>false</editMode>
		<helpMode>false</helpMode>
		<configMode>false</configMode>
		<autoRefreshed>false</autoRefreshed>
		<periodTime>0</periodTime>
		<allowJS>false</allowJS>
		<pageRefreshed>false</pageRefreshed>
		<showNumber>200</showNumber>
        <parameter>
			<name>url</name>
			<value>/TawDept/proxy_manage.do</value>
        </parameter>
        <role>role_admin</role>
    </portlet>
    <!--信息发布部分-->
    <portlet>
	    <name>infopublists</name>
		<path>/webPagePortlet.lp</path>
		<title>公共新闻</title>
		<icon>/portal/light/images/docs.gif</icon>
		<url>/infopub/TawInformation/list.do?boardId=145&amp;infoType=3</url><!-- 0315 by zhoucz -->
		<tag>portlet.tag.title.infopub</tag>
		<refreshMode>true</refreshMode>
		<editMode>false</editMode>
		<helpMode>false</helpMode>
		<configMode>false</configMode>
		<autoRefreshed>false</autoRefreshed>
		<periodTime>0</periodTime>
		<allowJS>false</allowJS>
		<pageRefreshed>false</pageRefreshed>
		<showNumber>200</showNumber>
        <parameter>
			<name>url</name>
			 <value>/infopub/TawInformation/list.do?boardId=145&amp;infoType=3</value><!-- 0315 by zhoucz -->
        </parameter>
        <role>role_member,role_public,role_admin</role>
    </portlet>
    <portlet>
	    <name>infopublist</name>
		<path>/webPagePortlet.lp</path>
		<title>公共信息</title>
		<icon>/portal/light/images/docs.gif</icon>
		<url>/template/information.jsp</url>
		<tag>portlet.tag.title.infopub</tag>
		<refreshMode>true</refreshMode>
		<editMode>false</editMode>
		<helpMode>false</helpMode>
		<configMode>false</configMode>
		<autoRefreshed>false</autoRefreshed>
		<periodTime>0</periodTime>
		<allowJS>false</allowJS>
		<pageRefreshed>false</pageRefreshed>
		<showNumber>200</showNumber>
        <parameter>
			<name>url</name>
			<value>/template/information.jsp</value>
        </parameter>
        <role>role_admin</role>
    </portlet>
    <!-- 070320 zhoucz test begin -->
        <portlet>
	    <name>infopublist_test1</name>
		<path>/webPagePortlet.lp</path>
		<title>公共信息测试1</title>
		<icon>/portal/light/images/docs.gif</icon>
		<url>/eoms_struts/test.jsp</url>
		<tag>portlet.tag.title.infopub</tag>
		<refreshMode>true</refreshMode>
		<editMode>false</editMode>
		<helpMode>false</helpMode>
		<configMode>false</configMode>
		<autoRefreshed>false</autoRefreshed>
		<periodTime>0</periodTime>
		<allowJS>false</allowJS>
		<pageRefreshed>false</pageRefreshed>
		<showNumber>200</showNumber>
         <parameter>
			<name>url</name>
			<value>/test.jsp</value>
        </parameter>
        <role>role_member,role_public,role_admin</role>
    </portlet>
    <!-- 070320 test end -->
    <portlet>
	    <name>infopubborad</name>
		<path>/webPagePortlet.lp</path>
		<title>公告版</title>
		<icon>/portal/light/images/docs.gif</icon>
		<url>/template/board.jsp</url>
		<tag>portlet.tag.title.infopub</tag>
		<refreshMode>true</refreshMode>
		<editMode>false</editMode>
		<helpMode>false</helpMode>
		<configMode>false</configMode>
		<autoRefreshed>false</autoRefreshed>
